include:
  - project: 'mobile/renovate-runner'
    file: '.gitlab-ci.yml'

stages:
  - health
  - release
  - deploy

before_script:
  - echo $CI_PROJECT_PATH
  - fvm install && fvm flutter upgrade
  - fvm flutter pub get
  - (cd example ; fvm install && fvm flutter pub get)


after_script:
  - git status
  - rm -rf .fvm/flutter_sdk
  - rm -rf example/.fvm/flutter_sdk

health_check:
  stage: health
  variables:
    CI_TIMEOUT: 120
  tags:
    - werf-m1
  script:
    - ./scripts/analyze_for_errors.sh
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master|main|develop)$/
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success

test:
  stage: health
  variables:
    CI_TIMEOUT: 120
  needs:
    - health_check
  tags:
    - werf-m1
  artifacts:
    when: always
    expire_in: "1 days"
    reports:
      junit:
        - junit-report.xml
  before_script:
    - export PATH="$PATH:.fvm/flutter_sdk/bin"
    - fvm flutter pub global activate junitreport
  script:
    - fvm flutter test --file-reporter json:tojunit.json
    - cat tojunit.json | $HOME/.pub-cache/bin/tojunit --output junit-report.xml
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master|main|develop)$/
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success


check:android:
  stage: health
  variables:
    CI_TIMEOUT: 120
  needs:
    - health_check
  tags:
    - werf-m1
  script:
    - cd example
    - fvm flutter build apk --debug
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master|main|develop)$/
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success

check:ios:
  stage: health
  variables:
    CI_TIMEOUT: 120
  needs:
    - health_check
  tags:
    - werf-m1
  script:
    - cd example
    - fvm flutter build ipa --debug --no-codesign
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master|main|develop)$/
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success

release:
  stage: release
  cache: {}
  tags:
    - werf-m1
  variables:
    CI: 1
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master|main)$/
      when: always
  before_script:
    - git tag -d $(git tag -l)
    - git fetch --tags --force
    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog @semantic-release/git conventional-changelog-conventionalcommits
  script:
    - semantic-release
