include: package:lints/recommended.yaml

analyzer:
  errors:
    always_declare_return_types: warning

linter:
  rules:
    close_sinks: true
    sort_constructors_first: false
    avoid_classes_with_only_static_members: false
    avoid_void_async: false
    avoid_positional_boolean_parameters: false
    avoid_function_literals_in_foreach_calls: false
    prefer_constructors_over_static_methods: false
    sort_unnamed_constructors_first: false
    sized_box_for_whitespace: false
    sort_pub_dependencies: false
    avoid_unnecessary_containers: false
    use_setters_to_change_properties: false

    # @melvspace: extra rules
    always_declare_return_types: true
    always_use_package_imports: true
    cancel_subscriptions: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unnecessary_breaks: true
